### ISSUE TITLE
Create alert does not support 'Extra Properties' that is possible through the UI

### ISSUE THREAD

**Issue by eyal-stratoscale** [opsgenie/opsgenie-go-sdk#14]
When I want to create a new alert, it is not possible to create extra properties.
In the UI, it is possible.

**Comment by halitokumus** [comment]
Thanks for reporting, we'll look into it and add the Extra Properties support.

**Comment by posener** [comment]
No need, your support team helped me with that -it is already supported in the `Details` variable.
