### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by ameissnersofi** [opsgenie/opsgenie-go-sdk#18]
What’s the timeline for getting a fully functional SDK using the V2 apis?

**Comment by bkaganyildiz** [comment]
Hi @ameissnersofi we partially updated our SDK. Currently it supports Alert, Heartbeat, User and Notification. And soon it will support the Schedule. It's going to take sometime to update all of it. But we'll definitely update SDK every once the implementation of an endpoint is done.

**Comment by cglrkn** [comment]
We created a new sdk which is working with V2 API's: https://github.com/opsgenie/opsgenie-go-sdk-v2
