### ISSUE TITLE
V2: AlertID from Create()

### ISSUE THREAD

**Issue by grubernaut** [opsgenie/opsgenie-go-sdk#20]
Currently using a v2 client and calling `create()` returns an `*AsyncRequestResponse`. Is it possible either now or in the future to return the `ID` of the created alert either with the returned request response struct, or with a subsequent call using the returned request ID?

**Comment by bkaganyildiz** [comment]
Hi @grubernaut , we generally love to refactor our code. Thank you for creating issue about. We'll definitely look into it. After analysis we may update alertv2.

**Comment by cglrkn** [comment]
We updated our new sdk which will is using V2 API's: https://github.com/opsgenie/opsgenie-go-sdk-v2
