### ISSUE TITLE
OpsGenieScheduleV2Client does not provide GetTimeline method

### ISSUE THREAD

**Issue by JosephSalisbury** [opsgenie/opsgenie-go-sdk#25]
Looking at https://docs.opsgenie.com/docs/schedule-api#section-get-schedule-timeline, I would expect a `GetTimeline` method, similar to the v1 client (see https://godoc.org/github.com/opsgenie/opsgenie-go-sdk/client#OpsGenieScheduleClient)

**Comment by digitalcrab** [comment]
Hello guys, any progress about this implementation? It was a bit of surprise to see "API v1 is deprecated" without having the same functionality implemented in SDK for a new version of API. Thanks

**Comment by gwkunze** [comment]
I've added a PR #27 which adds it. Until that gets merged you can import `github.com/gwkunze/opsgenie-gosdk` instead of `github.com/opsgenie/opsgenie-gosdk` (The master branch has all the import paths updated so golang can import it)

**Comment by cglrkn** [comment]
We released a new GO SDK. https://github.com/opsgenie/opsgenie-go-sdk-v2
