### ISSUE TITLE
Heartbeat List still using V1 API

### ISSUE THREAD

**Issue by cmaloney** [opsgenie/opsgenie-go-sdk#28]
I'm trying to use the Heartbeat API but when I do a List I get an error:

Unable to list existing heartbeats to sync: Client error occurred; Response Code: 410, Response Body: Heartbeat API v1 is deprecated. Please refer https://docs.opsgenie.com/docs/heartbeat-api for details of the new version

I think this is because the v1 api is still used for list: https://github.com/opsgenie/opsgenie-go-sdk/blob/master/client/opsgenie_heartbeat_client.go#L11

There is a v2 of the heartbeat REST api from what I can see: https://docs.opsgenie.com/docs/heartbeat-api#section-list-heartbeats

Happy to submit a PR to move to the new API if that would be useful

**Comment by cglrkn** [comment]
We released a new GO SDK. https://github.com/opsgenie/opsgenie-go-sdk-v2
