### ISSUE TITLE
support for Who is On Call API

### ISSUE THREAD

**Issue by czerasz** [opsgenie/opsgenie-go-sdk#38]
Any plans to add support for https://docs.opsgenie.com/docs/who-is-on-call-api?

```
https://api.opsgenie.com/v2/schedules/:scheduleIdentifier/on-calls
```

**Comment by cemkucuk** [comment]
hi @czerasz
opsgenie-go-sdk is deprecated, please use https://github.com/opsgenie/opsgenie-go-sdk-v2
